package com.parakett.metrics;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.util.Calendar;
import java.util.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.HashMap;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.parakett.JsonUtils;

public class MetricsDB {

    private static Connection _mConnection = null;

    private static final HashMap<String, String> _tableCreateSQL = new HashMap<>();

    private static PreparedStatement _mTokenMetricInsertStatement = null;
    private static PreparedStatement _mRequestMetricInsertStatement = null;

    static {
        _tableCreateSQL.put("TOKENS",
                "CREATE TABLE TOKENS(ID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), MODEL VARCHAR(64), CREATED_AT TIMESTAMP, INPUT_TOKENS INT, OUTPUT_TOKENS INT)");
        _tableCreateSQL.put("MODEL_REQUESTS",
                "CREATE TABLE MODEL_REQUESTS(ID INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), MODEL VARCHAR(64), START_TIME TIMESTAMP, END_TIME TIMESTAMP, TOTAL_DURATION INT, STATUS_CODE INT)");
    }

    public static void initialize() throws MetricsException {

        String homeDir = System.getProperty("user.home");

        // Construct the URL pointing inside the home directory
        String dbURL = "jdbc:derby:" + homeDir + "/fsmetrics;create=true";
        try {
            _mConnection = DriverManager.getConnection(dbURL);
            createTablesAsNeeded();
        } catch (Exception e) {
            throw new MetricsException(e);
        }
    }

    private static void createTablesAsNeeded() throws SQLException {
        DatabaseMetaData dbmd = _mConnection.getMetaData();
        for (String table : _tableCreateSQL.keySet()) {
            try (ResultSet rs = dbmd.getTables(null, null, table, new String[] { "TABLE" })) {
                if (!rs.next()) {
                    _mConnection.createStatement().executeLargeUpdate(_tableCreateSQL.get(table));
                }
            }
        }
    }

    public static void addTokenMetric(String model, int inTokens, int outTokens) throws MetricsException {
        if (_mTokenMetricInsertStatement == null) {
            String sql = "INSERT INTO TOKENS(MODEL, CREATED_AT, INPUT_TOKENS, OUTPUT_TOKENS) VALUES(?,?,?,?)";
            try {
                _mTokenMetricInsertStatement = _mConnection.prepareStatement(sql);
            } catch (SQLException e) {
                throw new MetricsException(e);
            }
        }

        try {
            _mTokenMetricInsertStatement.setString(1, model);
            _mTokenMetricInsertStatement.setTimestamp(2, new Timestamp(new Date().getTime()));
            _mTokenMetricInsertStatement.setInt(3, inTokens);
            _mTokenMetricInsertStatement.setInt(4, outTokens);
            _mTokenMetricInsertStatement.executeUpdate();
        } catch (SQLException e) {
            throw new MetricsException(e);
        }
    }

    public static void addRequestMetricForModel(String model, Date startTime, Date endTime, int status)
            throws MetricsException {
        if (_mRequestMetricInsertStatement == null) {
            String sql = "INSERT INTO MODEL_REQUESTS(MODEL, START_TIME, END_TIME, TOTAL_DURATION, STATUS_CODE) VALUES(?,?,?,?,?) ";
            try {
                _mRequestMetricInsertStatement = _mConnection.prepareStatement(sql);
            } catch (SQLException e) {
                throw new MetricsException(e);
            }
        }

        try {
            long diff = endTime.getTime() - startTime.getTime();
            _mRequestMetricInsertStatement.setString(1, model);
            _mRequestMetricInsertStatement.setTimestamp(2, new Timestamp(startTime.getTime()));
            _mRequestMetricInsertStatement.setTimestamp(3, new Timestamp(endTime.getTime()));
            _mRequestMetricInsertStatement.setLong(4, diff);
            _mRequestMetricInsertStatement.setInt(5, status);
            _mRequestMetricInsertStatement.executeUpdate();
        } catch (SQLException e) {
            throw new MetricsException(e);
        }
    }

    public static ObjectNode getTotalMetricForModel(String model) throws MetricsException {
        String sql = "SELECT SUM(INPUT_TOKENS) AS TOTAL_INPUT_TOKENS, SUM(OUTPUT_TOKENS) AS TOTAL_OUTPUT_TOKENS FROM TOKENS WHERE MODEL=?";
        try (PreparedStatement stmt = _mConnection.prepareStatement(sql)) {
            stmt.setString(1, model);

            ResultSet rs = stmt.executeQuery();
            int inputTokens = 0;
            int outputTokens = 0;
            if (rs.next()) {
                inputTokens = rs.getInt("TOTAL_INPUT_TOKENS");
                outputTokens = rs.getInt("TOTAL_OUTPUT_TOKENS");
            }

            ObjectNode ret = JsonUtils.MAPPER.createObjectNode();
            ret.put("inputTokens", inputTokens);
            ret.put("outputTokens", outputTokens);
            return ret;

        } catch (SQLException e) {
            throw new MetricsException(e);
        }
    }

    public static ObjectNode getTotalMetricForModelForDate(String model, Date date) throws MetricsException {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);

        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        Timestamp startOfDay = new Timestamp(cal.getTimeInMillis());

        cal.set(Calendar.HOUR_OF_DAY, 23);
        cal.set(Calendar.MINUTE, 59);
        cal.set(Calendar.SECOND, 59);
        cal.set(Calendar.MILLISECOND, 999);
        Timestamp endOfDay = new Timestamp(cal.getTimeInMillis());

        String sql = "SELECT SUM(INPUT_TOKENS) AS TOTAL_INPUT_TOKENS, SUM(OUTPUT_TOKENS) AS TOTAL_OUTPUT_TOKENS " +
                "FROM TOKENS " +
                "WHERE MODEL = ? AND CREATED_AT BETWEEN ? AND ?";

        int inputTokens = 0;
        int outputTokens = 0;

        try (
                PreparedStatement stmt = _mConnection.prepareStatement(sql)) {

            stmt.setString(1, model);
            stmt.setTimestamp(2, startOfDay);
            stmt.setTimestamp(3, endOfDay);

            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    // Derby returns 0 via getInt() if the SUM result is NULL (no rows matched)
                    inputTokens = rs.getInt("TOTAL_INPUT_TOKENS");
                    outputTokens = rs.getInt("TOTAL_OUTPUT_TOKENS");
                }
            }
        } catch (SQLException e) {
            throw new MetricsException(e);
        }

        ObjectNode ret = JsonUtils.MAPPER.createObjectNode();
        ret.put("inputTokens", inputTokens);
        ret.put("outputTokens", outputTokens);
        return ret;
    }

    public static ObjectNode getTotalMetricForModelFrom(String model, Date date) throws MetricsException {
        Timestamp fromTimestamp = new Timestamp(date.getTime());

        String sql = "SELECT SUM(INPUT_TOKENS) AS TOTAL_INPUT_TOKENS, SUM(OUTPUT_TOKENS) AS TOTAL_OUTPUT_TOKENS " +
                "FROM TOKENS " +
                "WHERE MODEL = ? AND CREATED_AT >= ?";

        int inputTokens = 0;
        int outputTokens = 0;

        try (PreparedStatement pstmt = _mConnection.prepareStatement(sql)) {

            pstmt.setString(1, model);
            pstmt.setTimestamp(2, fromTimestamp);

            try (ResultSet rs = pstmt.executeQuery()) {
                if (rs.next()) {
                    // getInt() automatically handles SQL NULLs by returning 0
                    inputTokens = rs.getInt("TOTAL_INPUT_TOKENS");
                    outputTokens = rs.getInt("TOTAL_OUTPUT_TOKENS");
                }
            }
        } catch (SQLException e) {
            throw new MetricsException(e);
        }

        ObjectNode ret = JsonUtils.MAPPER.createObjectNode();
        ret.put("inputTokens", inputTokens);
        ret.put("outputTokens", outputTokens);

        return ret;
    }

    public static ObjectNode getTotalRequestMetricForModel(String model) throws MetricsException {
        String sql = "SELECT COUNT(*) AS TOTAL_REQUESTS, AVG(TOTAL_DURATION) AS AVG_DURATION, MAX(TOTAL_DURATION) AS MAX_DURATION, MIN(TOTAL_DURATION) AS MIN_DURATION FROM MODEL_REQUESTS WHERE MODEL=?";
        try (PreparedStatement stmt = _mConnection.prepareStatement(sql)) {
            stmt.setString(1, model);

            ResultSet rs = stmt.executeQuery();
            int count = 0;
            long avgDuration = 0, maxDuration = 0, minDuration = 0;
            if (rs.next()) {
                count = rs.getInt("TOTAL_REQUESTS");
                avgDuration = rs.getInt("AVG_DURATION");
                maxDuration = rs.getInt("MAX_DURATION");
                minDuration = rs.getInt("MIN_DURATION");
            }

            ObjectNode ret = JsonUtils.MAPPER.createObjectNode();
            ret.put("count", count);
            ret.put("avgDuration", avgDuration);
            ret.put("maxDuration", maxDuration);
            ret.put("minDuration", minDuration);
            return ret;

        } catch (SQLException e) {
            throw new MetricsException(e);
        }
    }

    public static ObjectNode getRequestMetricForModelForToday(String model, Date date) throws MetricsException {
        Calendar cal = Calendar.getInstance();
        cal.setTime(date);

        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 0);
        Timestamp startOfDay = new Timestamp(cal.getTimeInMillis());

        cal.set(Calendar.HOUR_OF_DAY, 23);
        cal.set(Calendar.MINUTE, 59);
        cal.set(Calendar.SECOND, 59);
        cal.set(Calendar.MILLISECOND, 999);
        Timestamp endOfDay = new Timestamp(cal.getTimeInMillis());

        String sql = "SELECT COUNT(*) AS TOTAL_REQUESTS, AVG(TOTAL_DURATION) AS AVG_DURATION, MAX(TOTAL_DURATION) AS MAX_DURATION, MIN(TOTAL_DURATION) AS MIN_DURATION FROM MODEL_REQUESTS WHERE MODEL=? "
                +
                " AND (START_TIME BETWEEN ? AND ?)";
        try (PreparedStatement stmt = _mConnection.prepareStatement(sql)) {
            stmt.setString(1, model);
            stmt.setTimestamp(2, startOfDay);
            stmt.setTimestamp(3, endOfDay);

            ResultSet rs = stmt.executeQuery();
            int count = 0;
            long avgDuration = 0, maxDuration = 0, minDuration = 0;
            if (rs.next()) {
                count = rs.getInt("TOTAL_REQUESTS");
                avgDuration = rs.getInt("AVG_DURATION");
                maxDuration = rs.getInt("MAX_DURATION");
                minDuration = rs.getInt("MIN_DURATION");
            }

            ObjectNode ret = JsonUtils.MAPPER.createObjectNode();
            ret.put("count", count);
            ret.put("avgDuration", avgDuration);
            ret.put("maxDuration", maxDuration);
            ret.put("minDuration", minDuration);
            return ret;

        } catch (SQLException e) {
            throw new MetricsException(e);
        }
    }

}
